name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-11-jdk git unzip
          sudo apt install -y libffi-dev libssl-dev zlib1g-dev libjpeg-dev
          sudo apt install -y libgstreamer1.0-dev libunwind-dev  # Fix missing dependency
          pip install --upgrade cython buildozer
          sudo apt install -y gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
               gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav \
               gstreamer1.0-tools

      - name: Install Android SDK and Build Tools
        run: |
          # Install Android SDK and build tools
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
          sdkmanager "tools" "platforms;android-29" "build-tools;29.0.3"
          
      - name: Build APK
        run: |
          buildozer android debug
          buildozer android release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: WebViewApp-APK
          path: bin/
