name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-11-jdk git unzip
          sudo apt install -y libffi-dev libssl-dev zlib1g-dev libjpeg-dev
          sudo apt install -y libgstreamer1.0-dev libunwind-dev  # Fix missing dependency
          pip install --upgrade cython buildozer
          sudo apt install -y gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
               gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav \
               gstreamer1.0-tools

      - name: Install Android SDK command-line tools
        run: |
          # Download and install the Android SDK command-line tools
          mkdir -p $HOME/Android/Sdk
          cd $HOME/Android/Sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          rm commandlinetools-linux-7583922_latest.zip

          # Add SDK tools to the PATH
          echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

          # Accept licenses and install build-tools and platforms
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
          
      - name: Build APK
        run: |
          buildozer android debug
          buildozer android release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: WebViewApp-APK
          path: bin/
