name: Build APK

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Android SDK
        uses: reactivecircus/android-sdk@v2  # This sets up Android SDK easily

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-11-jdk git unzip
          pip install cython buildozer

      - name: Build APK using Buildozer
        run: |
          buildozer android debug  # Builds the APK

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WebViewApp-APK
          path: bin/
